services:
  auth-service:
    build: .
    ports:
      - '8080:8080'
    environment:
      - PORT=8080
      - DATABASE_URL=postgres://postgres:postgres@db:5432/auth?sslmode=disable
      - JWT_SECRET=supersecret
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=auth
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
